"""
constants_mapper.py

QuCalc-native structural observables and bridge estimates.

This rewrite intentionally removes:
- fixed hand-picked histories,
- surrogate logistic-map stand-ins,
- tuned normalization factors masquerading as derivations.

Every reported quantity is derived from:
1. canonical histories generated by twist_core.py, and
2. where geometry is needed, the current holographic.py bridge.

Some constants remain unsupported. Those are reported honestly as
'not yet QuCalc-native' rather than being filled in by unrelated models.
"""

from __future__ import annotations

import math
from collections import Counter
from statistics import geometric_mean
from typing import Dict, List, Optional, Sequence, Tuple

from holographic import project_history
from twist_core import (
    bound_action_estimate,
    calculate_action,
    conjugate_history,
    generate_histories,
    is_admissible_history,
    is_zfa,
    local_free_action,
    spatial_free_action,
    validate_history,
)


class ConstantsMapper:
    # ---------------------------------------------------------
    # 1. CODATA / reference values
    # ---------------------------------------------------------
    CODATA = {
        "pi": 3.141592653589793,
        "e": 2.718281828459045,
        "gamma": 0.5772156649015329,
        "feigenbaum_delta": 4.669201609102990,
        "alpha": 0.0072973525643,
        "G": 6.67430e-11,
    }

    # ---------------------------------------------------------
    # 2. SI constants for the laboratory bridge
    # ---------------------------------------------------------
    C = 299792458.0
    H_SI = 6.62607015e-34
    H_BAR = H_SI / (2 * math.pi)
    G_SI = CODATA["G"]

    L_P = math.sqrt((H_BAR * G_SI) / (C**3))
    T_P = math.sqrt((H_BAR * G_SI) / (C**5))
    M_P = math.sqrt((H_BAR * C) / G_SI)

    def __init__(
        self,
        history_string: Optional[str] = None,
        *,
        seeds: Sequence[str] = ("^", "<", "/", "+"),
        causal_horizon: int = 8,
        min_zfa_length: int = 4,
        max_histories: int = 256,
    ) -> None:
        self.history = history_string
        self.seeds = tuple(seeds)
        self.causal_horizon = causal_horizon
        self.min_zfa_length = min_zfa_length
        self.max_histories = max_histories

        self._stable_cache: Optional[List[str]] = None

        if self.history is not None:
            validate_history(self.history)

    # =========================================================
    # Core QuCalc ensemble
    # =========================================================

    def _stable_histories(self) -> List[str]:
        if self._stable_cache is not None:
            return self._stable_cache

        seen = set()
        stable: List[str] = []

        for seed in self.seeds:
            validate_history(seed)
            generated = generate_histories(
                seed,
                causal_horizon=self.causal_horizon,
                require_zfa=True,
                min_length=self.min_zfa_length,
            )
            for hist in generated:
                if hist in seen:
                    continue
                if not is_admissible_history(hist):
                    continue
                if not is_zfa(hist, min_length=self.min_zfa_length):
                    continue

                seen.add(hist)
                stable.append(hist)

                if len(stable) >= self.max_histories:
                    self._stable_cache = stable
                    return stable

        self._stable_cache = stable
        return stable

    def closure_counts_by_length(self) -> Dict[int, int]:
        counts = Counter(len(hist) for hist in self._stable_histories())
        return dict(sorted(counts.items()))

    def first_history(self) -> str:
        if self.history is not None:
            return self.history

        stable = self._stable_histories()
        if not stable:
            raise RuntimeError(
                "No stable QuCalc histories found. "
                "Increase causal_horizon or change seeds."
            )
        return stable[0]

    # =========================================================
    # Structural observables
    # =========================================================

    @staticmethod
    def _relative_error_percent(
        value: Optional[float], target: Optional[float]
    ) -> Optional[float]:
        if value is None or target is None or target == 0:
            return None
        return abs(value - target) / abs(target) * 100.0

    @staticmethod
    def _spherical_arc_length(history: str) -> float:
        """
        Sum geodesic arc lengths between successive projected prefix states
        on the unit sphere produced by holographic.project_history(history).
        """
        projections = project_history(history)
        if len(projections) < 2:
            return 0.0

        total = 0.0
        points = [p.xyz for p in projections]

        for left, right in zip(points, points[1:]):
            dot = float(left[0] * right[0] + left[1] * right[1] + left[2] * right[2])
            dot = max(-1.0, min(1.0, dot))
            total += math.acos(dot)

        return total

    def emerge_pi(self) -> Optional[float]:
        """
        QuCalc-native pi bridge:

        For each stable history, project the prefix states via holographic.py,
        compute the total geodesic perimeter on the unit sphere, and divide by
        the sphere diameter (2). For great-circle-like closures this yields π.
        """
        estimates: List[float] = []

        for hist in self._stable_histories():
            arc = self._spherical_arc_length(hist)
            if arc > 0:
                estimates.append(arc / 2.0)

        if not estimates:
            return None
        return sum(estimates) / len(estimates)

    def emerge_e(self) -> Optional[float]:
        """
        QuCalc-native e proxy:

        Use the cumulative growth base of distinct stable closures by history
        length. This is no longer a hand-picked fixed-history amplitude trick.
        """
        counts = self.closure_counts_by_length()
        if not counts:
            return None

        cumulative = 0
        bases: List[float] = []

        for length, count in counts.items():
            cumulative += count
            if length > 0 and cumulative > 1:
                bases.append(cumulative ** (1.0 / length))

        if not bases:
            return None

        # geometric mean gives a stable characteristic growth base
        return geometric_mean(bases)

    def emerge_gamma(self) -> Optional[float]:
        """
        QLF harmonic excess over the ordered stable-closure ensemble:

            gamma_QLF(N) = H_N - ln N

        where N is the number of distinct stable QuCalc histories in the
        current ensemble.
        """
        N = len(self._stable_histories())
        if N < 2:
            return None

        harmonic = sum(1.0 / k for k in range(1, N + 1))
        return harmonic - math.log(N)

    def emerge_alpha(self) -> Optional[float]:
        """
        QLF local/spatial ratio:

        alpha_QLF = total local folds / total spatial folds
        across the stable QuCalc ensemble.
        """
        total_local = 0
        total_spatial = 0

        for hist in self._stable_histories():
            local = hist.count("+") + hist.count("-")
            spatial = len(hist) - local
            total_local += local
            total_spatial += spatial

        if total_spatial == 0:
            return None

        return total_local / total_spatial

    def emerge_feigenbaum(self) -> Optional[float]:
        """
        Not yet QuCalc-native.

        The previous implementation used a logistic map, which is not a
        derivation from the canonical twist core. Until a true QuCalc
        renormalization / period-doubling operator exists, return None.
        """
        return None

    def emerge_G(self) -> Optional[float]:
        """
        Not yet QuCalc-native.

        The previous implementation used an explicit 1e-11 scale normalization,
        which was effectively hand-tuning. Until curvature is derived directly
        from QuCalc network geometry without fitted normalization, return None.
        """
        return None

    # =========================================================
    # Reporting
    # =========================================================

    @staticmethod
    def _format_constant_line(
        label: str,
        value: Optional[float],
        reference: Optional[float],
        derivation_note: str,
        *,
        sci: bool = False,
    ) -> str:
        if value is None:
            return (
                f"{label:<28}: not yet QuCalc-native "
                f"[{derivation_note}]"
            )

        if sci:
            value_str = f"{value:.6e}"
            ref_str = f"{reference:.6e}" if reference is not None else "n/a"
        else:
            value_str = f"{value:.10f}"
            ref_str = f"{reference:.10f}" if reference is not None else "n/a"

        if reference is None:
            return f"{label:<28}: {value_str} [{derivation_note}]"

        err = abs(value - reference) / abs(reference) * 100.0
        return (
            f"{label:<28}: {value_str} "
            f"(ref {ref_str}, error {err:.6f}%) "
            f"[{derivation_note}]"
        )

    def generate_constants_report(self) -> str:
        stable = self._stable_histories()
        counts = self.closure_counts_by_length()

        pi_val = self.emerge_pi()
        e_val = self.emerge_e()
        gamma_val = self.emerge_gamma()
        alpha_val = self.emerge_alpha()
        delta_val = self.emerge_feigenbaum()
        G_val = self.emerge_G()

        lines = [
            "=== QLF CONSTANTS / STRUCTURAL OBSERVABLES REPORT ===",
            f"Seeds                         : {self.seeds}",
            f"Causal horizon                : {self.causal_horizon}",
            f"Minimum ZFA length            : {self.min_zfa_length}",
            f"Stable histories collected    : {len(stable)}",
            f"Counts by length              : {counts}",
            "-" * 72,
            self._format_constant_line(
                "pi",
                pi_val,
                self.CODATA["pi"],
                "mean spherical arc/diameter ratio of projected QuCalc closures",
            ),
            self._format_constant_line(
                "e",
                e_val,
                self.CODATA["e"],
                "characteristic growth base of cumulative stable-closure counts",
            ),
            self._format_constant_line(
                "gamma",
                gamma_val,
                self.CODATA["gamma"],
                "harmonic excess of ordered stable-closure ensemble",
            ),
            self._format_constant_line(
                "alpha",
                alpha_val,
                self.CODATA["alpha"],
                "local/spatial fold ratio across stable QuCalc histories",
            ),
            self._format_constant_line(
                "feigenbaum_delta",
                delta_val,
                self.CODATA["feigenbaum_delta"],
                "requires a true QuCalc renormalization cascade",
            ),
            self._format_constant_line(
                "G",
                G_val,
                self.CODATA["G"],
                "requires scale-free curvature from QuCalc network geometry",
                sci=True,
            ),
            "-" * 72,
            "Interpretation:",
            "  - π, e, γ, and α are now computed from the refactored QuCalc core",
            "    and/or the current holographic bridge.",
            "  - δ and G are intentionally left unsupported until a genuine",
            "    QuCalc-native derivation exists.",
            "  - This report is therefore more internally honest than the old",
            "    demo-oriented mapper, even where the numerical agreement is worse.",
        ]
        return "\n".join(lines)

    # =========================================================
    # Per-history laboratory bridge
    # =========================================================

    def extract_time_folds(self, history: Optional[str] = None) -> Tuple[str, int, int]:
        hist = history or self.first_history()
        validate_history(hist)
        time_folds = "".join(ch for ch in hist if ch in ("+", "-"))
        return time_folds, time_folds.count("+"), time_folds.count("-")

    def extract_topological_action(
        self, history: Optional[str] = None
    ) -> Tuple[int, int, int, str]:
        hist = history or self.first_history()
        validate_history(hist)

        e_spatial_free = spatial_free_action(hist)
        e_local_free = local_free_action(hist)
        e_bound_total = bound_action_estimate(hist)
        time_folds, _, _ = self.extract_time_folds(hist)

        return e_spatial_free, e_local_free, e_bound_total, time_folds

    def generate_laboratory_report(self, history: Optional[str] = None) -> str:
        hist = history or self.first_history()
        validate_history(hist)

        action = calculate_action(hist)
        adjoint = conjugate_history(hist)
        e_spatial_free, e_local_free, e_bound_total, time_folds = (
            self.extract_topological_action(hist)
        )

        length_m = e_spatial_free * self.L_P
        time_s = e_local_free * self.T_P if e_local_free > 0 else float("inf")

        if time_s == float("inf"):
            time_str = "inf"
        else:
            time_str = f"{time_s:.6e}"

        return "\n".join(
            [
                "--- QLF Laboratory Translation Report ---",
                f"History String                  : {hist}",
                f"Adjoint                         : {adjoint}",
                f"Admissible                      : {is_admissible_history(hist)}",
                f"ZFA                             : {is_zfa(hist, min_length=self.min_zfa_length)}",
                f"Total Logical Action            : {len(hist)}",
                f"Action Tuple (v,h,d,l)          : {action}",
                "",
                "=== SPATIAL EMERGENCE (QLF bridge) ===",
                f"  Spatial Free Action           : {e_spatial_free} twists",
                f"  Planck-length Bridge          : {length_m:.6e} meters",
                "",
                "=== LOCAL / TEMPORAL EMERGENCE (QLF bridge) ===",
                f"  Time Folds (+/- subsequence)  : '{time_folds}'",
                f"  Local Free Action             : {e_local_free} twists",
                f"  Planck-time Bridge            : {time_str} seconds",
                "",
                "=== BOUND STRUCTURE ===",
                f"  Bound Action Estimate         : {e_bound_total}",
                "",
                "Note:",
                "  This laboratory report is a bridge translation in Planck units.",
                "  It is not yet a full derivation of SI observables from QLF.",
            ]
        )


if __name__ == "__main__":
    mapper = ConstantsMapper()
    print(mapper.generate_constants_report())
    print()
    print(mapper.generate_laboratory_report())
