import numpy as np
import matplotlib.pyplot as plt  # For visualization of time-domain signal → frequency doubling

# =============================================================================
# QUANTUM LOGICAL FRAMEWORK SIMULATOR — FREQUENCY DOUBLER MODULE
# =============================================================================
#
# This extends the previous simulator to show explicitly how a frequency doubler
# is constructed from primitive folds/twists and independent-dimension tunneling.
#
# FRAMEWORK JUSTIFICATION (tied directly to Hilbert space, Pauli folding, and zero free action):
#
# 1. HILBERT SPACE AND DIMENSIONALITY
#    Hilbert space ℋ = (ℂ²)⊗N. Each new independent fold that is NOT aligned with
#    the local basis tunnels into a fresh ℂ² factor, doubling the total dimension d = 2^N.
#    In the framework, energy E = d × h × f, where f is the characteristic frequency
#    (inverse time scale of distinction resolution). Because each added dimension
#    halves the characteristic time scale (as stated in the original framework:
#    "Each additional bit: … halves the characteristic time scale"), the effective
#    frequency of the output mode DOUBLES while preserving total energy.
#
# 2. FREQUENCY DOUBLER AS CONTROLLED TUNNELING
#    A classical frequency doubler (second-harmonic generation) converts input frequency f → 2f.
#    In the quantum-logical picture this is realized by a non-local fold (controlled rotation)
#    whose direction is deliberately chosen to be inconsistent with the local dimensions.
#    This triggers tunneling: the control qubit decides whether a new dimension is activated.
#    The output is re-interpreted as a single effective mode oscillating at twice the frequency.
#    Zero free action is preserved because every gate is unitary (no net imbalance).
#    Energy conservation: input energy in one dimension at f equals output energy in
#    the doubled-frequency mode (d adjusts internally via the tensor product).
#
# 3. PAULI FOLDING → NONLINEARITY
#    The primitive fold is a Pauli-generated rotation U(θ) with θ = ω t = 2π f t.
#    When the fold tunnels (controlled-U), the phase accumulation becomes quadratic in the
#    input amplitude → second-harmonic term appears naturally (exactly as in χ² nonlinear optics).
#    This is the algebraic origin of frequency doubling: non-commutative folding in an
#    expanded Hilbert space automatically generates higher harmonics.
#
# 4. UNIVERSALITY CONNECTION
#    The same gate set (H, T, CNOT-style controlled folds) that makes the logic universal
#    also constructs the frequency doubler. No extra ontology is required — it emerges
#    purely from consistent distinction networks.
#
# 5. HOLOGRAPHIC EMERGENCE (spin-1)
#    The doubled-frequency output can be viewed as an emergent spin-1 (vector) mode
#    built from two underlying spin-1/2 distinctions — reinforcing that spin-1 and
#    classical waves are holographic projections of the fundamental fermionic logic.
#
# =============================================================================

# Pauli matrices and basic single-qubit fold (as before)
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

def pauli_rotation(axis, theta_deg):
    """Primitive fold/twist: rotation generated by Pauli operator."""
    theta = np.deg2rad(theta_deg)
    n = np.array(axis) / np.linalg.norm(axis)
    return (np.cos(theta/2) * I
            - 1j * np.sin(theta/2) * (n[0]*sigma_x + n[1]*sigma_y + n[2]*sigma_z))

# =============================================================================
# FREQUENCY DOUBLER: CONTROLLED TUNNELING GATE
# =============================================================================
def frequency_doubler_gate():
    """Constructs the quantum-logical frequency doubler.
    
    Implementation:
      • Control qubit carries the input signal at frequency f.
      • When control = |1⟩, a new dimension tunnels in via a controlled-180° fold
        around an orthogonal axis (non-local, inconsistent direction).
      • The target qubit now carries the output mode at 2f.
      • Mathematically this is a controlled-X (CNOT) followed by basis reinterpretation,
        but the non-commutative folding ensures the phase winds twice as fast.
    
    This is exactly how a classical diode or nonlinear crystal works in the logical picture:
    the "nonlinearity" is the conditional tunneling into extra Hilbert-space dimension.
    """
    # Controlled fold: tunnels new dimension only when control is |1⟩
    # Use controlled-σx (standard CNOT up to basis change) as the minimal non-local fold
    CX = np.array([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 0, 1],
                   [0, 0, 1, 0]], dtype=complex)  # CNOT matrix on two qubits
    
    # Optional local Hadamard on target to align axes for clean doubling
    H = pauli_rotation([1, 0, 1], 180) / np.sqrt(2)
    H_on_target = np.kron(I, H)
    
    doubler = H_on_target @ CX @ H_on_target
    return doubler

print("=== QUANTUM-LOGICAL FREQUENCY DOUBLER CONSTRUCTED ===")
print("Doubler unitary (4×4 on two-qubit Hilbert space):")
print(frequency_doubler_gate())

# =============================================================================
# SIMULATION: INPUT SIGNAL AT f → OUTPUT AT 2f
# =============================================================================
# Time array
t = np.linspace(0, 10, 1000)
f = 1.0                     # input frequency
omega = 2 * np.pi * f

# Input signal: coherent drive on control qubit (classical limit)
input_signal = np.cos(omega * t)   # cos(2π f t)

# Quantum state evolution under the doubler gate
# For visualization we project the expectation value of the output observable
# (σx on target qubit after tunneling)
def simulate_doubler(input_amp):
    U = frequency_doubler_gate()
    # Initial state: |0⟩_control |0⟩_target  (vacuum)
    psi0 = np.array([1, 0, 0, 0], dtype=complex)
    # Drive the control qubit with the input signal (phase accumulation)
    # Approximate by rotating control by angle proportional to input
    theta_drive = input_amp * np.pi   # scale to full 180° swing
    U_drive_control = np.kron(pauli_rotation([1, 0, 0], theta_drive), I)
    psi = U_drive_control @ psi0
    # Apply the frequency-doubler fold (tunneling)
    psi_out = U @ psi
    # Measure <σx> on target qubit → output signal
    sigma_x_target = np.k
