"""
SPACETIME GENERATOR: Emergent Intervals from QuCalc Logic

This module models how discrete topological operations dynamically generate 
macroscopic space (x = E/h) and local time (t = h/E). It differentiates between 
action that "lines up" (Space) and action that "oscillates" (Time).
"""

class SpacetimeGenerator:
    # Planck's topological constant (h): The 4 fundamental twists required 
    # to form a minimal closed 2D boundary.
    H_CONSTANT = 4.0 

    def __init__(self, history_string):
        """
        Initializes the generator with a specific QuCalc history string.
        """
        self.history = history_string
        self.total_twists = len(history_string)

    def calculate_action_distribution(self):
        """
        Separates the total logical action into Free Action (E_free) 
        and Bound Action (E_bound).
        """
        # Calculate net un-canceled twists (Free Action) - consistent signed version
        net_v = abs(self.history.count('^') - self.history.count('v'))
        net_h = abs(self.history.count('<') - self.history.count('>'))
        net_d = abs(self.history.count('/') - self.history.count('\\'))
        net_l = abs(self.history.count('+') - self.history.count('-'))
        
        e_free = float(net_v + net_h + net_d + net_l)
        
        # Bound Action is the topological energy locked in ZFA cycles
        e_bound = float(self.total_twists - e_free)
        
        return e_free, e_bound

    def generate_space(self, e_free):
        """
        Space (x = E/h): Generated when twists line up in a 3D perspective 
        without contradiction. The outward projection of the manifold.
        """
        if e_free == 0:
            return 0.0
        x = e_free / self.H_CONSTANT
        return x

    def generate_time(self, e_bound):
        """
        Time (t = h/E): The temporal interval (clock tick) generated by 
        oscillating ZFA cycles. High bound energy ticks the clock faster.
        """
        if e_bound <= 0:
            return float('inf') # A perfectly straight line experiences no internal time (photon limit)
        t = self.H_CONSTANT / e_bound
        return t

    def get_clock_frequency(self, t_interval):
        """
        The frequency at which the local light cone is clocked (f = 1/t).
        """
        if t_interval == float('inf'):
            return 0.0
        return 1.0 / t_interval

    def model_spacetime(self):
        """
        Evaluates the history string and outputs the generated 
        spacetime geometry and clocking metrics.
        """
        e_free, e_bound = self.calculate_action_distribution()
        
        x_space = self.generate_space(e_free)
        t_time = self.generate_time(e_bound)
        f_clock = self.get_clock_frequency(t_time)

        report = {
            "History String": self.history,
            "Total Logical Action": self.total_twists,
            "Free Action (E_free)": e_free,
            "Bound Action (E_bound)": e_bound,
            "Generated Space (x = E_free / h)": x_space,
            "Local Time Interval (t = h / E_bound)": t_time,
            "Oscillation Frequency (Clock Speed)": f_clock
        }
        return report

# --- Clean Demonstration ---
if __name__ == "__main__":
    print("=== Spacetime Emergence Examples ===\n")
    
    # Clean photon-like string (pure free action)
    photon_string = "^^^^<<<<////"
    photon_generator = SpacetimeGenerator(photon_string)
    print("Photon (pure space):")
    for k, v in photon_generator.model_spacetime().items():
        print(f"  {k}: {v}")
    
    # Clean bound particle-like string
    fermion_string = "^>v<^>v<^^>><<vv"
    fermion_generator = SpacetimeGenerator(fermion_string)
    print("\nFermion (pure time):")
    for k, v in fermion_generator.model_spacetime().items():
        print(f"  {k}: {v}")
