"""
TOPOLOGY RESOLVER: Holographic Boundary Filtering and Unitarity Validator.

This module acts as the "Physics Engine" of the Quantum Logical Framework.
It enforces Zero Free Action (ZFA), verifies computable unitarity via 
adjoint evolution, and prunes topological contradictions at the causal light cone.
"""

class TopologyResolver:
    # Adjoint mapping for the 8-axis logic
    CONJUGATE_MAP = {
        '^': 'v', 'v': '^',
        '<': '>', '>': '<',
        '/': '\\', '\\': '/',
        '+': '-', '-': '+'
    }

    def __init__(self, light_cone_limit=12):
        """
        Initialize the resolver with a strictly defined causal boundary.
        Histories that fail to close within this limit dissipate into the vacuum.
        """
        self.light_cone_limit = light_cone_limit

    def measure_net_action(self, history_string):
        """
        Calculates the topological imbalance across all four logical axes.
        Returns a tuple representing (Vertical, Horizontal, Depth, Local).
        """
        v = history_string.count('^') - history_string.count('v')
        h = history_string.count('<') - history_string.count('>')
        d = history_string.count('/') - history_string.count('\\')
        l = history_string.count('+') - history_string.count('-')
        
        return (v, h, d, l)

    def is_zero_free_action(self, history_string):
        """
        A history string achieves ZFA if all topological actions strictly cancel out,
        representing a stable, closed manifold.
        """
        action_tuple = self.measure_net_action(history_string)
        return all(axis_net == 0 for axis_net in action_tuple)

    def get_adjoint(self, history_string):
        """
        Computes the Hermitian Conjugate (E_dagger) of a history string.
        Rule: Reverse the sequence (transpose) and invert each twist (conjugate).
        """
        reversed_sequence = history_string[::-1]
        return "".join([self.CONJUGATE_MAP[twist] for twist in reversed_sequence])

    def verify_unitarity(self, history_string):
        """
        Proves that a closed history string is strictly unitary.
        E + E_dagger must annihilate perfectly to the Void (ZFA).
        """
        adjoint = self.get_adjoint(history_string)
        evolution_cycle = history_string + adjoint
        return self.is_zero_free_action(evolution_cycle)

    def resolve_bulk(self, candidate_histories):
        """
        The Holographic Filter: Processes raw paths (the 'bulk') generated by QuCalc.
        Returns only those histories that are logically consistent and physically observable.
        """
        stable_observables = []
        dissipated = 0
        contradictions = 0

        for history in candidate_histories:
            # 1. Causal Pruning (Light Cone Enforcement)
            if len(history) > self.light_cone_limit:
                dissipated += 1
                continue
            
            # 2. Holographic Boundary Check (ZFA)
            if self.is_zero_free_action(history):
                # 3. Unitarity Verification (Hermitian Closure)
                if self.verify_unitarity(history):
                    stable_observables.append(history)
                else:
                    # Failsafe: Should theoretically never trigger if ZFA is true,
                    # but serves as a strict mathematical audit.
                    contradictions += 1 
            else:
                # Open loops or unbalanced strings
                contradictions += 1

        return {
            "stable_events": stable_observables,
            "dissipated_paths": dissipated,
            "topological_contradictions": contradictions
        }

# --- Self-Evident Example Execution ---
if __name__ == "__main__":
    resolver = TopologyResolver(light_cone_limit=10)
    
    # A mix of raw generated strings simulating output from qucalc_engine.py
    raw_paths = [
        "^<v>",         # 2D Loop (Stable ZFA)
        "^</+-",        # Open path (Contradiction)
        "^^vv<<>>",     # Complex 2D Loop (Stable ZFA)
        "^>v<+-\\/-",   # Invalid (Unbalanced Local axis)
        "^<v>^<v>^<v>"  # Exceeds light cone limit of 10 (Dissipates)
    ]
    
    print("--- Resolving Bulk Histories ---")
    results = resolver.resolve_bulk(raw_paths)
    
    print(f"\nStable Observables ({len(results['stable_events'])}):")
    for event in results['stable_events']:
        print(f" [+] {event} (Verified Unitary)")
        
    print(f"\nFiltered out {results['topological_contradictions']} topological contradictions.")
    print(f"Pruned {results['dissipated_paths']} paths at the causal light cone.")
