import numpy as np

# =============================================================================
# QUANTUM LOGICAL FRAMEWORK SIMULATOR — EXTENDED
# =============================================================================
#
# This builds directly on the previous simulator. New material demonstrates:
#   • Each "fold" or "twist" = a unitary rotation generated by a Pauli operator
#     (non-commutative multiplication in the local Hilbert space ℂ²).
#   • A fold/twist can be:
#       – Local: rotation axis consistent with existing dimensions → single-qubit gate.
#       – Independent dimension tunneling: the fold direction is NOT consistent locally.
#         This "tunnels" into a higher-dimensional Hilbert space by tensoring with a
#         new qubit (new ℂ² factor). The non-alignment creates entanglement or
#         controlled operations.
#   • Quantum logic gates are constructed exactly from these folds.
#   • Universality: the generated gates can approximate ANY unitary on ANY finite-
#     dimensional Hilbert space, hence construct ALL possible quantum-logical systems.
#
# Justification of assumptions (tied to Hilbert space and framework):
# 1. Hilbert space ℋ = (ℂ²)⊗N for N qubits. Each new independent fold adds a tensor
#    factor (doubles the dimension). This is how "tunneling" works: a fold whose
#    direction does not commute with the local basis projectors must act on a new
#    logical degree of freedom → dim(ℋ) → 2^N.
# 2. Pauli matrices generate ALL single-qubit unitaries via U = exp(-i θ/2 n·σ).
#    This is the Lie algebra su(2) ≅ unit quaternions (as before). Non-commutativity
#    enforces the 720° closure rule.
# 3. When the fold direction is "not consistent locally", the operator cannot be
#    written as a tensor product of local rotations; it couples qubits (controlled
#    or entangling gate). This is the algebraic origin of entanglement and the
#    emergence of higher-spin (spin-1) collective modes.
# 4. Zero free action is preserved because every gate is unitary (preserves the
#    inner product on ℋ) and each primitive fold is balanced (no net action).
# 5. Universality follows from the Solovay-Kitaev theorem: any finite set of gates
#    that generates a dense subgroup of SU(2^N) (including one entangling gate) can
#    approximate any quantum logic system to arbitrary precision. In our picture,
#    this means ALL possible consistent distinction networks (all logical systems)
#    can be synthesized from the primitive folds.
#
# Energy relation reminder (unchanged):
#    E = d × h × f   where d = dim(ℋ) = 2^N.
#
# =============================================================================

# Basic Pauli operators on single-qubit Hilbert space ℂ²
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

# =============================================================================
# 1. SINGLE-QUBIT GATES FROM LOCAL FOLDS / TWISTS
# =============================================================================
def pauli_rotation(axis, theta_deg, global_phase=False):
    """A single fold/twist = rotation generated by a Pauli.
    This is the matrix representation of a unit-quaternion rotation.
    If global_phase=True, we keep the exact -i factors (physically irrelevant)."""
    theta = np.deg2rad(theta_deg)
    n = np.array(axis) / np.linalg.norm(axis)
    U = (np.cos(theta/2) * I
         - 1j * np.sin(theta/2) * (n[0]*sigma_x + n[1]*sigma_y + n[2]*sigma_z))
    return U if global_phase else U / np.exp(1j*np.angle(U[0,0]))  # optional phase removal

print("=== 1. Local folds → single-qubit logic gates ===")
print("X gate (180° fold around x) =", pauli_rotation([1,0,0], 180))
print("Z gate (180° fold around z) =", pauli_rotation([0,0,1], 180))
print("Hadamard gate (fold around (x+z) axis by 180° + phase) =", 
      pauli_rotation([1,0,1], 180) / np.sqrt(2))  # standard H up to phase

# T-gate (π/4 phase) — a twist around z
T = np.array([[1, 0], [0, np.exp(1j*np.pi/4)]], dtype=complex)
print("T-gate (π/4 twist around z) =", T)

# =============================================================================
# 2. INDEPENDENT-DIMENSION TUNNELING → MULTI-QUBIT / ENTANGLING GATES
# =============================================================================
# When the fold direction is NOT aligned with existing local dimensions,
# we tensor with a new qubit (new Hilbert-space factor) and the non-commuting
# action becomes a controlled operation.

def controlled_rotation(control_axis, target_axis, theta_deg):
    """A fold that tunnels into a new dimension.
    The control qubit's state decides whether the target fold is applied.
    This is the algebraic origin of entanglement: the twist direction
    is orthogonal to the local basis of the control qubit."""
    theta = np.deg2rad(theta_deg)
    # Controlled-U where U is rotation on target
    U_target = pauli_rotation(target_axis, theta_deg, global_phase=True)
    # Full operator on two qubits: |0><0| ⊗ I + |1><1| ⊗ U
    CU = np.kron(np.diag([1, 0]), I) + np.kron(np.diag([0, 1]), U_target)
    return CU

print("\n=== 2. Non-local folds (independent-dimension tunneling) ===")
print("Controlled-Z (fold on target only if control is |1>, z-direction) =")
print(controlled_rotation([0,0,1], [0,0,1], 180))  # CZ gate

# Standard CNOT gate: can be built from Hadamard + controlled-Z + Hadamard
# (H on target, CZ, H on target)
H = pauli_rotation([1,0,1], 180) / np.sqrt(2)
CNOT = np.kron(I, H) @ controlled_rotation([0,0,1], [0,0,1], 180) @ np.kron(I, H)
print("Constructed CNOT gate (universal entangler) =")
print(CNOT)

# =============================================================================
# 3. ENERGY-DIMENSIONALITY SCALING WITH NEW TUNNELED DIMENSIONS
# =============================================================================
h = 6.62607015e-34  # Planck's constant
f = 1.0
def hilbert_dim(N_qubits):
    return 2 ** N_qubits

for N in [1, 2, 3]:
    d = hilbert_dim(N)
    E = d * h * f
    print(f"\nFor {N} qubits (after {N-1} tunnelings): d = {d}, E = {E:.4e} J")

# =============================================================================
# 4. UNIVERSALITY: CONSTRUCTING ALL POSSIBLE LOGICAL SYSTEMS
# =============================================================================
print("\n=== 4. Universality — constructing ALL quantum-logical systems ===")
print("""The set {H, T, CNOT} (all built from primitive folds) is universal:
• Any single-qubit unitary (any local fold/twist) is generated densely by H and T.
• CNOT provides entanglement (non-local tunneling).
By the Solovay-Kitaev theorem, repeated combinations of these gates can approximate
ANY unitary U ∈ SU(2^N) to arbitrary precision ε.
Therefore every possible consistent network of distinctions — i.e., every quantum-
logical system that can exist in Hilbert space — can be synthesized.
In the framework: the full Hilbert space of all logical possibilities is reachable
from the zero-action primitive (one creation operator) via successive local and
non-local folds.""")

# Example: approximate a random two-qubit unitary using the constructed gates
# (in practice one would use a compiler; here we illustrate the principle)
print("\nExample: a random two-qubit unitary can be approximated by sequences")
print("of the above gates (H, T, CNOT) — the mathematical guarantee holds.")

# =============================================================================
# SUMMARY
# =============================================================================
print("\n=== FRAMEWORK SUMMARY ===")
print("• Each fold/twist = Pauli rotation on ℂ² (local) or controlled rotation (tunneling).")
print("• Non-consistent direction → new tensor factor → higher-dimensional Hilbert space.")
print("• All quantum logic gates are built this way.")
print("• The gate set is universal → ALL possible quantum-logical systems can be constructed.")
print("• Energy scales with total Hilbert dimensionality: E = 2^N × h × f.")
print("Run the code, modify axes/angles/N, and watch new dimensions tunnel in!")
