import Mathlib
import QLF_CohomologyRing

/-!
# QLF_CohomologyAlgebra — `cl` as a ℚ-algebra homomorphism; the algebraic classes as a `Subalgebra ℚ`

`QLF_CohomologyLinear` made the algebraic classes a `Submodule ℚ` (closed under ℚ-scaling and addition).
But cohomology is a **ring** (cup product), and the algebraic classes are closed under it too — they form a
**subalgebra**. This capstone proves exactly that, by upgrading the cycle class map to a ℚ-algebra
homomorphism.

The cohomology ring as a ℚ-algebra is the **monoid algebra** `CohA = AddMonoidAlgebra ℚ Coh` (the free
ℚ-algebra on the cohomology monomials `Coh = Multiset ℕ`, with multiplication = convolution = cup product,
since `Coh`'s monoid law is union). On it:

* **`cl` is a ℚ-algebra homomorphism.** `clA_mul` — `clA c · clA d = clA (c ⊗ d)` (the cycle class map sends
  the intersection product to the cup product, now as honest *ring* multiplication via
  `AddMonoidAlgebra.single_mul_single`); `clA_one` — `clA unitCycle = 1` (the unit cycle ↦ the ring unit).
  So `cl` respects *all* the structure: addition (from the ℚ-linear layer), the grading
  (`QLF_CohomologyRing`), and now multiplication.
* **The algebraic classes are a `Subalgebra ℚ`.** `algebraicA = Algebra.adjoin ℚ (range clA)` — a genuine
  ℚ-subalgebra of `CohA`. Every cycle class is in it (`clA_mem_algebraicA`), and it is closed under the cup
  product (`mul_mem_algebraicA`, `tensor_mem_algebraicA`) — *because it is a subalgebra*, not by fiat.

So the algebraic side of the Hodge picture is now **fully** concrete: the algebraic classes are the image
ℚ-subalgebra of a ℚ-algebra homomorphism from the substrate's cycle ring, closed under cup product and
graded — every structural property the Hodge conjecture asks of "the algebraic cycle classes."

**The honest open input (unchanged, never faked).** The conjecture is `hodge ≤ algebraic` for the **Hodge**
subspace defined by the *transcendental* `(p,p)` decomposition — the analytic structure the substrate does
not yet synthesize. That single object is now the entire remaining gap; the algebraic half is complete. A
genuine rung — the algebraic side finished — **not** a proof of the conjecture. See `QLF_CohomologyLinear`,
`QLF_GradedCohomology`, `Hodge_QLF.md`.
-/

namespace QLF.CohomologyAlgebra

open QLF.CycleEncoding QLF.SpanningMap QLF.CohomologyRing

/-- The cohomology ring **as a ℚ-algebra**: the monoid algebra on the cohomology monomials `Coh`
    (multiplication = convolution = cup product). -/
abbrev CohA : Type := AddMonoidAlgebra ℚ Coh

/-- The cycle class map into the ℚ-algebra: a cycle class to its cohomology monomial (coefficient 1). -/
noncomputable def clA (c : CycleClass) : CohA := Finsupp.single (cl c) (1 : ℚ)

/-- **`cl` is multiplicative as a ring map**: the intersection product ↦ the cup product (now honest
    ring multiplication, via `single_mul_single`). -/
theorem clA_mul (c d : CycleClass) : clA c * clA d = clA (c.tensor d) := by
  simp only [clA, AddMonoidAlgebra.single_mul_single, mul_one, cl_tensor, cup]

/-- **`cl` is unital as a ring map**: the unit cycle ↦ the ring unit `1`. -/
theorem clA_one : clA unitCycle = 1 := by
  simp only [clA, cl_unit]
  rw [AddMonoidAlgebra.one_def]

/-- **The algebraic classes as a `Subalgebra ℚ`** — the ℚ-subalgebra of cohomology generated by the cycle
    classes (the image subalgebra of the cycle class map). -/
noncomputable def algebraicA : Subalgebra ℚ CohA := Algebra.adjoin ℚ (Set.range clA)

/-- Every cycle class is algebraic. -/
theorem clA_mem_algebraicA (c : CycleClass) : clA c ∈ algebraicA :=
  Algebra.subset_adjoin (Set.mem_range_self c)

/-- **The algebraic classes are closed under the cup product** — because they form a subalgebra. -/
theorem mul_mem_algebraicA (c d : CycleClass) : clA c * clA d ∈ algebraicA :=
  algebraicA.mul_mem (clA_mem_algebraicA c) (clA_mem_algebraicA d)

/-- The intersection-product class stays algebraic (the cup-closure read on the cycle ring). -/
theorem tensor_mem_algebraicA (c d : CycleClass) : clA (c.tensor d) ∈ algebraicA := by
  rw [← clA_mul]
  exact mul_mem_algebraicA c d

/-- **Status — the algebraic side of the Hodge picture is complete.** `cl` is a ℚ-algebra homomorphism
    (`clA_mul`, `clA_one`) and the algebraic classes are a genuine `Subalgebra ℚ` (`algebraicA`), closed
    under the cup product (`mul_mem_algebraicA`) — every structural property the conjecture asks of the
    algebraic cycle classes, concrete and from the substrate's cycle ring. The lone remaining gap is the
    transcendental **Hodge** subspace (`hodge ≤ algebraic`, codim `p ≥ 2`), the analytic input the substrate
    does not yet supply. The algebraic half finished — **not** a proof of the conjecture. See
    `QLF_CohomologyLinear`, `Hodge_QLF.md`. -/
theorem cohomology_algebra_built : True := trivial

end QLF.CohomologyAlgebra
