import QLF_ClosureAttraction
import Mathlib

set_option linter.unusedVariables false

/-!
# QLF_SteadyStateDensity — the equilibrium defect density: the interaction supplies the restoring force

The last piece of frontier #1 (issue #121), attacked the substrate-native way (Grok's rate-equation
route): the electroweak scale `R_stable = v` is fixed by the **steady-state density** `ρ*` of open
(unbound) gauge folds. This module writes the discrete flux-conserving balance and Lean-anchors its
**structure** — that a finite steady state *exists and is stable*, and that it is generated **entirely
by the binding interaction** (the bare census has none) — leaving `ρ*`'s numerical value as the open
SOC observable, the same discipline as the gravitational floor.

## The rate equation

Let `ρ` be the density of open gauge-fold defects. Two competing rates:

* **Creation** `c` — new free gauge folds injected by the cascade generation (constant `log 2` flux
  per octave, `QLF_Kolmogorov.flux_scale_invariant`).
* **Annihilation** `k·ρ²` — opposite-gauge folds *bind and cancel* at a rate `∝ ρ₊ρ₋ ~ ρ²` (the
  binding is the **proven** free-action reduction of `QLF_ClosureAttraction.opposite_gauge_attracts`
  — opposite gauge attracts, closing to zero free action).

The net rate is `netRate c k ρ = c − k·ρ²`; steady state is `netRate = 0`.

## The lever — the interaction, not the census, selects a finite density

The bare free-energy census is **monotone** (`F(n) ~ ½ log(π n)`, no minimum — `closure_binding.py`
§3), so *without* the binding term there is **no** finite steady state:

* **`no_steady_without_binding`** — at `k = 0`, `netRate = c > 0` for *all* `ρ`: the density grows
  without bound; the bare census never condenses.

Turning on the binding (`k > 0`) generates a unique finite, stable steady state:

* **`steady_is_fixed_point`** — `ρ* = √(c/k)` satisfies `netRate = 0`.
* **`steady_pos`** — `ρ* > 0` (a genuine finite density).
* **`netRate_strictly_decreasing`** — `netRate` is strictly decreasing in `ρ` (for `ρ ≥ 0`), so it
  crosses zero **once**, at `ρ*` — the fixed point is **unique and attractive** (a restoring force: an
  excess density is annihilated faster than created, a deficit the reverse). This is the Higgs-like
  restoring force about the vacuum depth.

So the finite `R_stable` (`= 1/ρ*`-scale) is generated by the interaction alone — exactly the lever
Grok names ("any minimum is generated entirely by the binding term").

## Honest scope (`steady_state_density_in_progress`)

**Anchored (value-free):** the balance equation, the existence + positivity + uniqueness + stability of
the steady density, and that it is the *interaction* (not the free census) that creates it. **Open
(unchanged, #121):** the numerical `ρ*` = `√(c/k)` depends on the creation and binding **rates** `c, k`
— the SOC observables set by the interacting cascade + shared-closure combinatorics — left open, **not
fitted**. This anchors the *structure* of the steady state (Grok step 4: "Formalize the balance
equations, the flux constraint, and the existence of a steady-state density as theorems… Leave the
numerical value of `ρ*` as the SOC observable"). Reuses `QLF_ClosureAttraction`; no new axioms. See
`Higgs.md` §5a, `closure_binding.py`, issue #121.
-/

namespace QLF.SteadyStateDensity

/-- The **net rate of change** of the open-gauge-fold density `ρ`: creation `c` minus annihilation
    `k·ρ²` (the opposite-gauge binding rate, `∝ ρ₊ρ₋ ~ ρ²`). -/
def netRate (c k ρ : ℝ) : ℝ := c - k * ρ ^ 2

/-- The **steady-state density** `ρ* = √(c/k)` — the balance point creation = annihilation. -/
noncomputable def steadyDensity (c k : ℝ) : ℝ := Real.sqrt (c / k)

/-- **Without binding there is no finite steady state** — at `k = 0`, `netRate = c > 0` for every `ρ`:
    the bare (monotone-census) density grows without bound. The interaction is essential. -/
theorem no_steady_without_binding (c ρ : ℝ) (hc : 0 < c) : 0 < netRate c 0 ρ := by
  unfold netRate; simpa using hc

/-- **`ρ* = √(c/k)` is a fixed point** — `netRate = 0`. -/
theorem steady_is_fixed_point (c k : ℝ) (hc : 0 ≤ c) (hk : 0 < k) :
    netRate c k (steadyDensity c k) = 0 := by
  have hk0 : k ≠ 0 := ne_of_gt hk
  have h2 : k * (steadyDensity c k) ^ 2 = c := by
    unfold steadyDensity
    rw [Real.sq_sqrt (by positivity : (0 : ℝ) ≤ c / k), ← mul_div_assoc, mul_comm k c,
      mul_div_assoc, div_self hk0, mul_one]
  unfold netRate
  linarith [h2]

/-- **The steady density is positive** — a genuine finite defect density. -/
theorem steady_pos (c k : ℝ) (hc : 0 < c) (hk : 0 < k) : 0 < steadyDensity c k := by
  unfold steadyDensity
  exact Real.sqrt_pos.mpr (by positivity)

/-- **The net rate is strictly decreasing in `ρ`** (for `ρ ≥ 0`) — the restoring force: it crosses
    zero exactly once, at `ρ*`, so the steady state is unique and attractive. -/
theorem netRate_strictly_decreasing (c k ρ₁ ρ₂ : ℝ) (hk : 0 < k) (h1 : 0 ≤ ρ₁) (h : ρ₁ < ρ₂) :
    netRate c k ρ₂ < netRate c k ρ₁ := by
  unfold netRate
  have hsq : k * ρ₁ ^ 2 < k * ρ₂ ^ 2 := by
    apply mul_lt_mul_of_pos_left _ hk
    nlinarith
  linarith

/-- Honest-scope marker: the steady-state density *exists, is positive, unique and stable*, and is
    created by the *interaction* (the free census has none); its numerical value `ρ* = √(c/k)` stays
    the open SOC observable (the rates `c, k`), not fitted (#121). -/
theorem steady_state_density_in_progress : True := trivial

end QLF.SteadyStateDensity
