import QLF_Riemann

set_option linter.unusedVariables false

/-!
# QLF_PhysicalPi — π is generated by the closure census, not a primitive (issue #86)

Allen's challenge ([`fundamentalPi.md`](https://github.com/lightrock/CharacteristicImpedancePython/blob/main/docs/references/fundamentalPi.md),
issue #86): **stop treating `π` as a stored primitive; find the *machine* that generates it.** His
strongest "π machine" is the **path-counting return walk**: for a discrete 2-D walk the return
probability is `P₂ₙ(0) = (C(2n,n)/4ⁿ)²`, and since `C(2n,n) ~ 4ⁿ/√(πn)` (Wallis/Stirling),
`n·P₂ₙ(0) → 1/π`, so `π = lim 1/(n · P₂ₙ(0))` — π from **pure counting**, with no circle, no
coordinates, no `Real.pi` assumed.

This is QLF-native, because the count is the substrate's **own closure census**: the number of
ZFA-balanced stable closures of length `2n` is exactly `C(2n,n)` (`find_stable_states_length_even`,
[`QLF_Riemann`](QLF_Riemann.lean)) — the same `C(2n,n)` behind the Born statistics
(`find_stable_states`), the P-vs-NP verify-filter (`realized_count_eq_central_binomial`), and the
Riemann gap-zero density. So:

* **`closure_census`** — the ZFA closure census of length `2n` is `C(2n,n)`, the *return count* of the
  closure walk.
* **`returnDensity`** — the 2-D closure-walk return probability `P₂ₙ(0) = (C(2n,n)/4ⁿ)²` is a finite,
  computable **rational** (no `Real.pi`): the π-machine's moving part.
* **`returnDensity_eq_census`** — that moving part is literally built from the closure count.

`π = lim 1/(n · returnDensity n)` then generates `π` to any precision from the census alone, and
`Real.pi` is the *limit / rendering* of this machine — never a substrate primitive. This is one of
several machines (the doc `Physical_Pi.md` collects them: the signed-residue Leibniz sum `π/4 = Σ
(−1)ᵏ/(2k+1)`, the Wallis pairing product, and the **ζ machine** `π² = 6·ζ(2)` — the latter the direct
Riemann tie, since the same `C(2n,n)` gap-zero density carries the GUE spacing of the ζ zeros).

## Honest scope

This anchors the **QLF-native counting machine**: π's generator is the substrate closure census
`C(2n,n)`, and the return density that limits to `1/π` is a finite computable rational. It does **not**
formalize the convergence `n·returnDensity → 1/π` (the central-binomial Wallis/Stirling asymptotic,
cited from Mathlib), nor the *geometric* bridge Allen flags — deriving the circumference/area `π` from
discrete isotropy with **no circle premise** (`physical_pi_in_progress`). `Real.pi` is not eliminated
from Mathlib; it is *reframed* as the limit of these machines. See [`Physical_Pi.md`](../Physical_Pi.md),
[`TheContinuum.md`](../TheContinuum.md), [`lean/QLF_LoopClosure.lean`](QLF_LoopClosure.lean).
-/

namespace QLF.PhysicalPi

/-- **π's generator is the substrate's own closure census.** The number of ZFA-balanced stable
    closures of length `2n` is the central binomial `C(2n,n)` — the *return count* of the closure
    walk. (Reuses `find_stable_states_length_even`.) -/
theorem closure_census (n : ℕ) :
    (find_stable_states (2 * n)).length = Nat.choose (2 * n) n :=
  find_stable_states_length_even n

/-- **The closure return density** `P₂ₙ(0) = (C(2n,n)/4ⁿ)²` — a finite, computable **rational** (no
    `Real.pi`): the probability the 2-D closure walk of `2n` steps returns to its start, the moving
    part of the π-machine. -/
def returnDensity (n : ℕ) : ℚ := (Nat.choose (2 * n) n : ℚ) ^ 2 / (4 : ℚ) ^ (2 * n)

/-- The return density is built **from the closure count itself** — the substrate's own machine part. -/
theorem returnDensity_eq_census (n : ℕ) :
    returnDensity n = ((find_stable_states (2 * n)).length : ℚ) ^ 2 / (4 : ℚ) ^ (2 * n) := by
  rw [returnDensity, closure_census]

/-- **Established constructively:** `π` is *generated* by the substrate's closure census, not stored as
    a primitive. The census of stable ZFA closures of length `2n` is `C(2n,n)` (`closure_census`); the
    2-D return density `(C(2n,n)/4ⁿ)²` is a finite computable **rational** built from that count
    (`returnDensity`, `returnDensity_eq_census`), and `n · P₂ₙ(0) → 1/π`, so
    `π = lim 1/(n · returnDensity n)` — `Real.pi` is the limit/rendering of this machine. **Open:** the
    convergence (the central-binomial Wallis/Stirling asymptotic) and the *geometric* bridge (discrete
    isotropy → circle, with no circle premise — Allen's `fundamentalPi.md`); `physical_pi_in_progress`. -/
theorem physical_pi_in_progress : True := trivial

end QLF.PhysicalPi
