import QLF_Spin

set_option linter.unusedVariables false

/-!
# QLF_WeakChirality — the weak force is chiral, and only the left-handed neutrino enters the blanket

The weak force's defining feature is **parity violation** (V−A): it couples to one chirality only.
QLF already carries chirality as a verified twist invariant — the **perpendicular chirality**
`perpChirality = baryonNumber` (the 3-axis winding sign) and the **chiral charge** `chiralCharge` (the
signed gauge-twist count), both of which **negate under view-from-behind** (the antiparticle map =
conjugate-and-reverse, QLF's parity/charge-conjugation): `perpChirality_conj`, `chiralCharge_conj`,
`C_eq_motional_reversal`. So:

* **`weak_charge_parity_odd`** — the weak/chiral charge is **odd** under view-from-behind. A
  parity-symmetric force would treat a history and its mirror identically; the weak (chiral) charge does
  not. **Parity violation is structural.**

The neutrino is special. It is its own antiparticle (Majorana, `neutrino_majorana`), so:

* **`neutrino_no_perp_chirality`** — the Majorana neutrino has **zero perpendicular chirality**:
  self-conjugacy + parity-odd chirality force `perpChirality ν = − perpChirality ν = 0`. The neutrino has
  **no perpendicular-winding handedness**; its only handedness is **helical** — the flat `σy` spin
  relative to its motion.

**Jim's intuition — only the left-handed neutrino enters the Markov blanket.** The active neutrino
`^v = [up, down]` is the flat `σy` spatial spin (`fold_up_down : ^v = −I`); the weak isospin `su(2)` is
generated by the spatial twist axes (`weak_isospin_su2`, the `τ = iσ` on `σx/σy/σz`). A *right-handed /
sterile* neutrino is a **pure-gauge** sequence with no spatial twist (Beyond_Standard_Model §3) — it
carries no spatial axis for the weak isospin to act on, so it is a **weak singlet** that does not close
into the charged-current blanket. Only the spatially-twisted (left-handed) neutrino carries weak isospin
and is admitted. Parity violation **is** this admissibility asymmetry: of the two helicities, only the
one that closes into the weak blanket interacts.

## Scope

This anchors the **parity-odd weak charge** (V−A structure) and the **neutrino's helical-only
handedness** (zero perpendicular chirality from Majorana self-conjugacy), reusing
`perpChirality_conj` / `chiralCharge_conj` / `neutrino_majorana`. It does **not** build the full V−A
projector `P_L = (1−γ₅)/2` as a Lean operator, nor the helicity-vs-motion operator that would make "only
the left-handed neutrino closes" a theorem rather than a structural reading (`weak_chirality_in_progress`,
the same open weak-dynamics sector as `gauge_unification_in_progress`). See
[`CP-Violation-and-Chirality.md`](../CP-Violation-and-Chirality.md), [`Beta_Decay_Neutrino_Nature.md`](../Beta_Decay_Neutrino_Nature.md).
-/

namespace QLF.WeakChirality

open QLF QLF.Spin QLF.Majorana

/-- **Parity violation, structural.** Under view-from-behind (the antiparticle map), the weak/chiral
    charge is **odd**: both the perpendicular chirality and the chiral charge negate. A parity-symmetric
    force would treat `ts` and its mirror identically; the weak (chiral) charge does not — so the weak
    interaction violates parity by construction. Packages `perpChirality_conj` + `chiralCharge_conj`. -/
theorem weak_charge_parity_odd (ts : List Twist) :
    perpChirality (antiparticle ts) = - perpChirality ts ∧
    chiralCharge (antiparticle ts) = - chiralCharge ts :=
  ⟨perpChirality_conj ts, chiralCharge_conj ts⟩

/-- **The Majorana neutrino has no perpendicular chirality.** Being its own antiparticle
    (`neutrino_majorana`) while chirality is parity-odd (`perpChirality_conj`), the neutrino's
    perpendicular chirality equals its own negative, hence `0`. Its only handedness is **helical** (the
    flat `σy` spin relative to motion) — there is no perpendicular-winding handedness to flip, which is
    why a sterile (right-handed) neutrino has nothing left to be: only the left-helical state closes. -/
theorem neutrino_no_perp_chirality : perpChirality [Twist.up, Twist.down] = 0 := by
  have hm : antiparticle [Twist.up, Twist.down] = [Twist.up, Twist.down] := neutrino_majorana
  have h := perpChirality_conj [Twist.up, Twist.down]
  rw [hm] at h
  omega

/-- **Established:** the weak force is chiral — the weak/chiral charge is parity-odd
    (`weak_charge_parity_odd`), so the interaction violates parity by construction; and the Majorana
    neutrino has zero perpendicular chirality (`neutrino_no_perp_chirality`), its only handedness being
    helical. Read with the spatial weak-isospin `su(2)` (`weak_isospin_su2`), this is Jim's blanket
    admissibility: the pure-gauge (right-handed / sterile) neutrino carries no spatial isospin and does
    not close into the weak blanket — only the spatially-twisted left-handed neutrino is admitted.
    **Open:** the V−A projector and the helicity-vs-motion operator that would make
    "only-left-closes" a theorem (`weak_chirality_in_progress`). -/
theorem weak_chirality_in_progress : True := trivial

end QLF.WeakChirality
