import QLF_Pauli
import Mathlib

/-!
# QLF_StateSpace — the QLF phase group is μ₄ = the units of the Gaussian integers ℤ[i]

Hilbert space `ℂ^∞` is *too general* for QLF: it has continuum cardinality, **continuous `U(1)`
phases**, and infinite dimension — none of which a finite-information universe realizes (see
`QLF_Realizability`, `TheContinuum.md`). The QLF state space is the discrete, computable
substructure Hilbert space is the *completion* of: a finite-rank free module over the **Gaussian
integers `ℤ[i]`**, with phases in **`μ₄ = {±1, ±i}`** — the 4th roots of unity, the units of `ℤ[i]`.

This module machine-checks the load-bearing structural fact: the QLF **phase group**
(`QLF.PauliScalar`, the scalars `{+I, −I, +iI, −iI}` every balanced closure folds to,
`count_balanced_pauli_closed`) is exactly the cyclic group of order 4 = `μ₄`. Every phase is a 4th
root of unity, `i` generates, and the embedding into `ℂ` lands on the complex 4th roots of unity.
Since the generators `σx, σy, σz` have entries in `{0, ±1, ±i} = ℤ[i]`, amplitudes live over `ℤ[i]`
and Born probabilities are rational — *no continuum*. See `The_QLF_State_Space.md`.
-/

namespace QLF.StateSpace

open QLF

/-- **Every QLF phase is a 4th root of unity.** In the phase group `PauliScalar`, `p⁴ = 1` for
    every element — the group-native statement that the phases are `μ₄`. -/
theorem pauliScalar_pow_four_eq_one (p : PauliScalar) : p * p * p * p = 1 := by
  cases p <;> rfl

/-- **`i` generates — the group has order exactly 4.** None of `i`, `i²`, `i³` is the identity, so
    together with `i⁴ = 1` the phase group is cyclic of order 4 = `μ₄ = (ℤ[i])ˣ`. -/
theorem pauliScalar_i_order_four :
    PauliScalar.i ≠ 1 ∧
    PauliScalar.i * PauliScalar.i ≠ 1 ∧
    PauliScalar.i * PauliScalar.i * PauliScalar.i ≠ 1 := by
  decide

/-- The phase group embeds into `ℂ` as `i^k`. -/
def toComplex : PauliScalar → ℂ
  | .one    => 1
  | .i      => Complex.I
  | .negOne => -1
  | .negI   => -Complex.I

/-- **The image is the complex 4th roots of unity.** `(toComplex p)⁴ = 1` for every phase — the
    QLF phase group is *literally* `μ₄ ⊂ ℂˣ`, the units of the Gaussian integers `ℤ[i]`, not a
    continuous `U(1)`. -/
theorem toComplex_pow_four (p : PauliScalar) : (toComplex p) ^ 4 = 1 := by
  have hI : Complex.I ^ 4 = 1 := by
    rw [show (4 : ℕ) = 2 + 2 by norm_num, pow_add, Complex.I_sq]; norm_num
  cases p with
  | one    => simp only [toComplex]; norm_num
  | i      => simpa only [toComplex] using hI
  | negOne => simp only [toComplex]; norm_num
  | negI   =>
    simp only [toComplex]
    rw [show (-Complex.I) = (-1) * Complex.I by ring, mul_pow, hI]
    norm_num

/-- **Status — the QLF phase group is `μ₄ = (ℤ[i])ˣ`, machine-checked.** Every phase is a 4th root
    of unity (`pauliScalar_pow_four_eq_one`, `toComplex_pow_four`), generated by `i`
    (`pauliScalar_i_order_four`). With the `σ`-generators valued in `{0,±1,±i} = ℤ[i]`, QLF
    amplitudes live over the Gaussian integers and Born probabilities are rational — Hilbert space
    is the continuum *completion*, too general by exactly the continuous phases / infinite dimension
    it adds. See `The_QLF_State_Space.md`, `TheContinuum.md`. -/
theorem qlf_phase_group_is_mu4 : True := trivial

end QLF.StateSpace
