-- QLF_LocalClock.lean
-- The Markov-blanket-local-clock identity:
--
--   A QLF Markov blanket of topological depth R is a local clock whose
--   period in universal-substrate (Planck-event) ticks is exactly R, with
--   each ZFA closure event advancing the local clock by one tick and
--   contributing exactly log 2 nats of information.
--
-- This is the QLF realisation of Hitoshi Kitada's local-time framework
-- (gr-qc/9612043): each quantum subsystem carries its own clock,
-- generated by its own Hamiltonian evolution. In QLF, the Hamiltonian
-- generator is the per-event log 2 quantum (Lean-anchored as
-- zfa_closure_minimizes_free_energy in QLF_FreeEnergy.lean), and the
-- local clock is the cumulative event count — equivalently, the depth.
-- Universal time is the relational construct obtained by comparing
-- local clocks at different depths (Mach-style).
--
-- The theorem markov_blanket_local_clock packages this identity for any
-- constructible RhoProcess: its local-clock period equals the length of
-- its events trajectory, and its cumulative information equals the
-- period times log 2.
--
-- This is the per-event Lean anchor for Gap 1 of
-- Kitada_Local_Time_GR.md §3, and the foundational identity named
-- explicitly in Frequency_Synchronization.md §1.1.
--
-- Companion to:
--   • Frequency_Synchronization.md §1.1   — the foundational identity
--   • Kitada_Local_Time_GR.md §3 (Gap 1)   — the scoping doc that named
--                                            this as a research target
--   • QLF_RhoProcessBridge.lean            — supplies the events function
--                                            and rho_process_alignment_
--                                            saturates which this theorem
--                                            packages as a clock identity
--   • QLF_FreeEnergy.lean                  — supplies the per-event log 2
--                                            quantum

import QLF_RhoProcessBridge

namespace QLF

/-- **Local-clock period of a Markov blanket.**

    For a constructible RhoProcess `p`, the local-clock period is the
    length of its events trajectory — equivalently, its topological
    depth `R(p)` measured in universal-substrate (Planck-event) ticks.

    Each ZFA closure event contributes one tick of the local clock and
    advances the cumulative information by exactly `log 2` nats (the
    per-event MRE quantum).  See `markov_blanket_local_clock` below. -/
noncomputable def local_clock_period (p : RhoProcess) : ℕ :=
  (events p).length

/-- **The Markov-blanket-local-clock identity** — the Lean anchor for
    Gap 1 of `Kitada_Local_Time_GR.md` §3 and the foundational
    identity of `Frequency_Synchronization.md` §1.1.

    For any constructible RhoProcess `p`, the cumulative information
    encoded in the blanket's events trajectory equals the local-clock
    period times `log 2`:

    $$\\text{cumulative\\_kl}\\,(\\text{events}\\ p) \\;=\\; R(p) \\cdot \\log 2$$

    where `R(p) = local_clock_period p` is the depth.

    This packages two structural commitments as a single identity:

      • **Each event = one tick**.  The local clock advances by exactly
        one tick per ZFA closure event; the tick count equals the
        events-trajectory length, which equals the topological depth.

      • **Each tick = `log 2` nats**.  Each event saturates the per-event
        MRE quantum (Lean-anchored as `binary_kl_delta_uniform` and the
        family in `QLF_FreeEnergy.lean`); the total cumulative information
        equals the tick count times `log 2`.

    Together this is the QLF reading of Kitada's local-time framework
    (gr-qc/9612043): each Markov blanket IS a local clock, with the
    per-event log 2 quantum as the Hamiltonian generator and the depth
    as the elapsed local-time count.

    Proof: by `rho_process_alignment_saturates`, which establishes
    exactly this saturation for the cumulative KL.  The local-clock
    identity is just this theorem, re-packaged under the local-clock
    name. -/
theorem markov_blanket_local_clock (p : RhoProcess) :
    cumulative_kl (events p) = (local_clock_period p : ℝ) * Real.log 2 := by
  unfold local_clock_period
  exact rho_process_alignment_saturates p

/-- The information advanced per local-clock tick is exactly `log 2`.

    Equivalent restatement of `markov_blanket_local_clock` emphasising
    the per-tick content: dividing the cumulative information by the
    period gives `log 2`. -/
theorem local_clock_tick_is_log_two (p : RhoProcess)
    (h : local_clock_period p ≠ 0) :
    cumulative_kl (events p) / (local_clock_period p : ℝ) = Real.log 2 := by
  rw [markov_blanket_local_clock]
  have hpos : (local_clock_period p : ℝ) ≠ 0 := by
    exact_mod_cast h
  field_simp

end QLF
